services:
  tafuta:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: tafuta_app
    env_file: .env.dev
    ports:
      - "5000:5000"
    volumes:
      - ..:/app
    restart: unless-stopped
