version: '3.9'

services:
  backend:
    build:
      context: ../..
      dockerfile: backend/docker/Dockerfile
      args:
        ENV: dev
    container_name: tafuta_backend
    ports:
      - "5001:5000"
    volumes:
      - ../../backend:/app/backend
    environment:
      - FLASK_ENV=development
    command: flask run --reload
